// Generated by CoffeeScript 1.6.3
(function() {
  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

  Game.ClickCookie;

}).call(this);
